modLoader="javafml"
loaderVersion="[31,)"
license="LGPL-2.1"
issueTrackerURL="https://github.com/SkyBlade1978/BaseMetals/issues"

[[mods]]
modId="basemetals"
version="3.0.1.115021"
displayName="Base Metals"
displayURL="https://www.curseforge.com/minecraft/mc-mods/base-metals"
authors="Cyanobacterium, jriwanek, dshadowwolf, GetDizzy611, SkyBlade1978, the MMD Team"
description='''Adds real and fantasy metals, alloys, tools and armour. Crush ores with Crack Hammers, blend new metals and discover ores placed by OreSpawn.'''

[[dependencies.basemetals]]
modId="orespawn"
mandatory=true
versionRange="[4.1.0.115021,5.0.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.basemetals]]
modId="forge"
mandatory=true
versionRange="[31,)"
ordering="NONE"
side="BOTH"

[[dependencies.basemetals]]
modId="minecraft"
mandatory=true
versionRange="[1.15.2]"
ordering="NONE"
side="BOTH"
