modLoader="javafml"
loaderVersion="[36,)"
license="LGPL-2.1"
issueTrackerURL="https://github.com/MinecraftModDevelopmentMods/BaseMetals/issues"

[[mods]]
modId="basemetals"
version="3.1.0.116051"
displayName="Base Metals"
displayURL="https://www.curseforge.com/minecraft/mc-mods/base-metals"
authors="Cyanobacterium, jriwanek, dshadowwolf, GetDizzy611, SkyBlade1978, the MMD Team"
description='''Adds real and fantasy metals, alloys, tools and armour. Crush ores with Crack Hammers, blend new metals and discover ores placed by OreSpawn.'''

[[dependencies.basemetals]]
modId="orespawn"
mandatory=true
versionRange="[4.1.0.116051,5.0.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.basemetals]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.basemetals]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"
