modLoader="javafml"
loaderVersion="[37,38)"
license="LGPL-2.1"

[[mods]]
modId="basemetalsclientprobe"
version="1"
displayName="Base Metals Client Probe"
description='''Build-only packaged-client checks for Base Metals 1.17.1.'''

[[dependencies.basemetalsclientprobe]]
modId="basemetals"
mandatory=true
versionRange="[3.1.0.117011]"
ordering="AFTER"
side="CLIENT"

[[dependencies.basemetalsclientprobe]]
modId="orespawn"
mandatory=true
versionRange="[4.1.0.117011,5.0.0)"
ordering="AFTER"
side="CLIENT"

[[dependencies.basemetalsclientprobe]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1]"
ordering="NONE"
side="CLIENT"
